Update gtm

diff --git a/gtm b/gtm
--- a/gtm
+++ b/gtm
@@ -1,64 +1,63 @@
-declare -A SERVERS=(
-    ["phc.jericoo.site"]="124.6.181.27 124.8.181.28 124.6.181.171 124.6.181.31 124.6.181.160"
-) 
+#!/bin/bash
+## TFN VPN
+## Script to keep-alive your DNSTT server domain record query from target resolver/local dns server
+## Run this script excluded to your VPN tunnel (split vpn tunneling mode)
 
+## Your DNSTT Nameserver & your Domain `A` Record
+NS='phc.jericoo.site'
+## Repeat dig cmd loop time (seconds) (positive interger only)
+LOOP_DELAY=5
+
+## Add your DNS here
+declare -a HOSTS=('124.6.181.31' '124.6.181.171' '124.6.181.30' '124.6.181.160' '124.6.181.88' '124.6.181.26' '124.6.181.27' '124.6.181.25' '124.6.181.28')
+
+## Linux' dig command executable filepath
+## Select value: "CUSTOM|C" or "DEFAULT|D"
 DIG_EXEC="DEFAULT"
-
+## if set to CUSTOM, enter your custom dig executable path here
 CUSTOM_DIG=/data/data/com.termux/files/home/go/bin/fastdig
 
-
-VER=0
-
+######################################
+######################################
+######################################
+######################################
+######################################
+VER=0.1
 case "${DIG_EXEC}" in
-DEFAULT|D)
-    _DIG="$(command -v dig)"
-    ;;
-CUSTOM|C)
-    _DIG="${CUSTOM_DIG}"
-    ;;
+ DEFAULT|D)
+ _DIG="$(command -v dig)"
+ ;;
+ CUSTOM|C)
+ _DIG="${CUSTOM_DIG}"
+ ;;
 esac
-
 if [ ! $(command -v ${_DIG}) ]; then
-    printf ",DIG_EXEC & CUSTOM_DIG variables inside $( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )/$(basename "$0") file.\n"
-    exit 1
+ printf "%b" "Dig command failed to run, " \
+ "please install dig(dnsutils) or check " \
+ "\$DIG_EXEC & \$CUSTOM_DIG variable inside $( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )/$(basename "$0") file.\n" && exit 1
 fi
-
 endscript() {
-    unset LOOP_DELAY SERVERS _DIG DIG_EXEC T R M
-    exit 1
+ unset NS A LOOP_DELAY HOSTS _DIG DIG_EXEC CUSTOM_DIG T R M
+ exit 1
 }
-
 trap endscript 2 15
-
-check() {
-    for server in "${!SERVERS[@]}"; do
-        for host in ${SERVERS["$server"]}; do
-            T="${host}"
-            R="${server}"
-
-            ping -c 1 "${T}" &
-            host "${R}" &
-            
-            timeout -k 3 3 ${_DIG} @${T} "${R}"
-            if [ $? -eq 0 ]; then
-                M=32
-            else
-                M=31
-            fi
-            echo -e "\e[${M}m:${R} D:${T}\e[0m"
-        done
-    done
+check(){
+ for ((i=0; i<"${#HOSTS[*]}"; i++)); do
+  for R in "${NS}"; do
+   T="${HOSTS[$i]}"
+   [[ -z $(timeout -k 3 3 ${_DIG} @${T} ${R}) ]] && M=31 || M=32;
+   echo -e "\e[1;${M}m\$ R:${R} D:${T}\e[0m"
+   unset T R M
+  done
+ done
 }
-
-for server in "${!SERVERS[@]}"; do
-    echo -e "\e[34m${server}\e[0m -> ${SERVERS["$server"]}"
-done
-
-if [ "${LOOP_DELAY}" -eq 1 ]; then
-    let "LOOP_DELAY++"
-fi
-
+echo "DNSTT Keep-Alive script <Dexter Eskalarte>"
+echo -e "DNS List: [\e[1;34m${HOSTS[*]}\e[0m]"
+echo "CTRL + C to close script"
+[[ "${LOOP_DELAY}" -eq 1 ]] && let "LOOP_DELAY++";
 while true; do
-    check
-    sleep ${LOOP_DELAY}
-done && chmod +x ../data/data/com.termux/files/usr/bin/tfn; rm -rf gtm
+ check
+ echo 'PLEASE WAIT'
+ sleep ${LOOP_DELAY}
+done
+exit 0
